<div class="container">
    <div class="user-container">
    
        <h1><?php echo $this->translate('Register'); ?></h1>
        
        <?php
            if (!$this->enableRegistration) {
                print "Registration is disabled";
                return;
            }
            $form = $this->registerForm;
            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/register'));
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
            <table width="100%">
                <tbody>
                    <tr>
                        <td>
                            <?php foreach ($form as $element) : ?>
                             
                                <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                                    <?php
                                        if ('submit' != $element->getAttribute('type')) { ?>
                                            <label class="control-label"><?php echo $element->getLabel() ?></label>
                                            <?php
                                            $element->setAttribute('class', 'form-control')
                                                    ->setAttribute('placeholder', $element->getLabel());
                                        } else {
                                            $element->setAttribute('class', 'btn btn-primary');
                                            $submitElement = $element;
                                        }
                                        
                                        if ($element instanceof Zend\Form\Element\Captcha) {
                                            echo $this->formCaptcha($element);
                                        } else {
                                            if ('submit' != $element->getAttribute('type')) {
                                                echo $this->formElement($element);
                                            }
                                        }
                                        
                                        if ($this->formElementErrors($element)) : ?>
                                            <?php
                                            echo $this->formElementErrors()
                                                ->setMessageOpenFormat('<p class="help-block">')
                                                ->setMessageSeparatorString('</p><p class="help-block">')
                                                ->setMessageCloseString('</p>')
                                                ->render($element);
                                            ?>
                                        <?php endif; ?>
                                </div>
                             
                            <?php endforeach; ?>
                        </td>
                    </tr>
                </tbody>
                <?php /*if(!empty($error_message)): ?>
                    <thead>
                        <tr>
                            <td>
                                <p class="message-container message-danger">
                                    <?php echo $error_message ?>
                                </p>
                            </td>
                        </tr>
                    </thead>
                <?php endif*/ ?>
            </table>                            
            
            <div class="row">
                <div class="col-sm-6">
                    <?php echo $this->formElement($submitElement) ?>
                </div>
                <div class="col-sm-6 user-bar-signup">
                    <a class="user-link-signin" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign In'); ?></a>
                </div>
            </div>                
                
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
            
        <?php echo $this->form()->closeTag() ?>

    </div>
</div>