<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/layout.css'))
                        ->prependStylesheet($this->basePath('dragula/dragula.min.css'))
                        ->prependStylesheet($this->basePath('bootstrap-3.3.6/css/ie10-viewport-bug-workaround.css'))
                        ->prependStylesheet($this->basePath('bootstrap-3.3.6/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('bootstrap-3.3.6/js/ie-emulation-modes-warning.js'))
            ->prependFile($this->basePath('bootstrap-3.3.6/js/ie8-responsive-file-warning.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        
        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!--<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>-->
                        <a class="navbar-brand logo" href="#">
                            <img src="<?php echo $this->basePath('img/logo.png') ?>" height="50px"/>
                            <span class="logo-blue">Research</span>
                            <span class="logo-grey">Apps</span>
                        </a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                          <li><a href="#">Dashboard</a></li>
                          <li><a href="#">Settings</a></li>
                          <li><a href="#">Profile</a></li>
                          <li><a href="#">Help</a></li>
                        </ul>
                        <form class="navbar-form navbar-right">
                          <input type="text" class="form-control" placeholder="Search...">
                        </form>
                    </div>
                </div>
            </div>
        </nav>

        <?php echo $this->content; ?>
        
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/bootstrap-3.3.6/js/jquery.min.js"><\/script>')</script>        
        <?php
            echo $this->inlineScript()
                ->prependFile($this->basePath('js/layout.js'))
                ->prependFile($this->basePath('dragula/dragula.min.js'))
                ->prependFile($this->basePath('bootstrap-3.3.6/js/ie10-viewport-bug-workaround.js'))
                ->prependFile($this->basePath('bootstrap-3.3.6/js/holder.min.js'))
                ->prependFile($this->basePath('bootstrap-3.3.6/js/bootstrap.min.js'))

        ?>
    </body>
</html>
