<div class="banner">
	<img src="<?php echo $this->basePath('img/banner.jpg') ?>" id="banner-bg" alt="Research Apps" />
	<div class="bar">
		<div class="bottom-bar">
			<div class="container">
				<div class="banner-menu">
					<h2>We Build Custom Mobile Applications for Clinical Research</h2>
                    <h3>based on Apple ResearchKit and ResearchApps Platform </h3>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
				</div>
			</div>
		</div>
	</div>
</div>




				
					<div class="info">
				<div class="container">
					<h3>Мы будем рады Вам помочь сделать Ваш автомобиль <strong>безопасным!</strong></h3>
					<div class="row">
						<div class="col-sm-2 col">
							<img class="img-responsive" src="/templates/comcar/images/icon_delivery.png" alt="Comcar - доставка защиты для автомобиля" />
						</div>
						<div class="col-sm-4 col">
							<h4>Доставка и оплата</h4>
							<p>
								Мы осуществляем бесплатную доставку по г. Гродно до двери. Оплата наличными.
							</p>
							<p>
								Платная доставка по Республике Беларусь, партнером является компания Globel24...
							</p>
							<p align="right" class="delivery-bottom">
								<a href="/index.php/shipping">&rarr; узнать подробности</a>
							</a>
						</div>
						<div class="col-sm-2 col">
							<img class="img-responsive" src="/templates/comcar/images/icon_assembly.png" alt="Comcar - установка защиты"/>
						</div>
						<div class="col-sm-4 col">
							<h4>Установка</h4>
							<p>
								В нашем установочном центре Вас ждут следующие виды услуг:
							</p>
							<ul>
								<li>предварительная мойка двигателя паром;</li>
								<li>подбор и установка необходимого оборудования.</li>
							</ul>
							<p align="right">
								<a href="/index.php/assembling">&rarr; узнать подробности</a>
							</a>
						</div>
					</div>
				</div>
			</div>
				
					<div class="about">
				<div class="container">
					<div class="about-img">
						<img class="img-responsive" src="/templates/comcar/images/about_img.png" alt="Comcar - о компании" />
					</div>
					<div class="about-img-clear"></div>
					<h3>Компания <strong>COMCAR</strong></h3>
					<h4>Мы специализируемся на оптово-розничных продажах дополнительного оборудования для автомобилей и квадроциклов.</h4>
					<p class="logos">
						<img src="/templates/comcar/images/shadow-line.png" alt="Comcar"/><br />
						<img width="370px" src="/templates/comcar/images/logos.png" alt="Comcar - КОМФОРТ И БЕЗОПАСНОСТЬ ВАШЕГО АВТОМОБИЛЯ!" />
					</p>
					<p align="right">
						<br />
						<a href="http://vk.com/comcar_bel" target="_blank">мы Вконтакте &rarr;</a>
					</a>
				</div>
			</div>