<h1 class="page-header">Dashboard</h1>

<div class="editor-container">
    <div class="row">
        <div class="col-sm-6">
            <div id="editor-samples">
                <div class="editor-item">R1</div>
                <div class="editor-item">R2</div>
                <div class="editor-item">R3</div>
                <div class="editor-item">R4</div>
                <div class="editor-item">R5</div>
            </div>
        </div>
        <div class="col-sm-6">
            <div id="editor-storyboard">
            </div>
        </div>
    </div>
</div>
